// Auto-generated by the postman-to-k6 converter

import './libs/shim/core.js';
import './libs/shim/urijs.js';
import { group } from 'k6';

export const options = {
  vus: 10,
  duration: '30s',
  ext: {
    loadimpact: {
      // Project: blueskies
      projectID: 3663177,
      // Test runs with the same name groups test runs together.
      name: 'All endpoints',
    },
  },
};

const Request = Symbol.for('request');
postman[Symbol.for('initial')]({
  options,
  collection: {
    express: 'https://express-microservice.azurewebsites.net',
    net: 'https://dot-net-api.azurewebsites.net',
  },
});

export default function () {
  group('.NET API', function () {
    group('Systems', function () {
      postman[Request]({
        name: 'Get All Systems',
        id: '60e52fb6-a0c0-4b46-87f1-f76541de35d0',
        method: 'GET',
        address: '{{net}}/System/all',
      });

      postman[Request]({
        name: 'Get system by Id',
        id: '423ad1a5-53ee-412e-abac-ff20b3685a3f',
        method: 'GET',
        address: '{{net}}/System/get/2',
      });
    });

    group('Appliances', function () {
      postman[Request]({
        name: 'Get All Appliances',
        id: '8bbdd23b-6c07-4d30-9020-5f21505b97cb',
        method: 'GET',
        address: '{{net}}/Appliance/all',
      });

      postman[Request]({
        name: 'Get Appliance',
        id: '82f805ae-7e65-4ac3-902b-9c67a2fc70de',
        method: 'GET',
        address: '{{net}}/Appliance/get/10',
      });
    });

    group('Keys', function () {
      postman[Request]({
        name: 'Get All Keys',
        id: 'e308c52e-da58-40e7-9e5a-c7a816d1ffe1',
        method: 'GET',
        address: '{{net}}/Key/all',
      });

      postman[Request]({
        name: 'Get All Business Keys',
        id: 'd8929dd2-4dbc-4dc2-9b24-0b67cb89c979',
        method: 'GET',
        address: '{{net}}/Key/allBusiness',
      });
    });

    group('Location Data', function () {
      postman[Request]({
        name: 'Get map box api key',
        id: '4c25a9af-d00a-4908-807f-51095b473ebb',
        method: 'GET',
        address: '{{net}}/locationData/mapboxkey',
      });

      postman[Request]({
        name: 'Get Location Data',
        id: 'a6698a9c-a87f-491f-99b0-31ce2f243f2d',
        method: 'GET',
        address: '{{net}}/locationData/getLocationData/-25.78097/28.267354',
      });
    });

    group('Admin Stats', function () {
      group('System Usage', function () {
        postman[Request]({
          name: 'Get System Usage',
          id: '2364d545-3274-47db-805e-bdc68c2bbf73',
          method: 'GET',
          address: '{{net}}/adminstats/all',
        });
      });
    });

    group('Reports', function () {
      postman[Request]({
        name: 'Get All Reports',
        id: '7eda0df0-a689-40bd-b81d-4eca6ae6030a',
        method: 'GET',
        address: '{{net}}/Report/all',
      });

      postman[Request]({
        name: 'Get User Reports',
        id: 'e4399509-9714-4ca3-922b-76d137bb5d44',
        method: 'GET',
        address: '{{net}}/Report/getUserReports/69',
      });

      postman[Request]({
        name: 'Get Report',
        id: 'e46ccdc5-b53d-4c82-b7a4-ed1c06e9cc8d',
        method: 'GET',
        address: '{{net}}/Report/get/122',
      });
    });

    group('Report All Appliances', function () {
      postman[Request]({
        name: 'Get All Appliance Report',
        id: '866d0c10-ec19-4c7e-8121-9319ce2fa949',
        method: 'GET',
        address: '{{net}}/ReportAllAppliance/all',
      });

      postman[Request]({
        name: 'Get Report By Report Id',
        id: '4bbae466-4326-458c-be23-8d5d32465723',
        method: 'GET',
        address: '{{net}}/ReportAllAppliance/getByReportId/91',
      });
    });

    group('Report Appliance', function () {
      postman[Request]({
        name: 'Get All Report Appliances',
        id: 'b8bc112a-1945-4b65-977e-46fd4e419d7c',
        method: 'GET',
        address: '{{net}}/ReportAppliance/all',
      });

      postman[Request]({
        name: 'Get Appliances in Report',
        id: '0e53f84d-497d-4c65-b67b-462a16cdc1d2',
        method: 'GET',
        address: '{{net}}/ReportAppliance/getAppliancesInReport/91',
      });

      postman[Request]({
        name: 'Get Reports With Appliance',
        id: 'ca1c958d-3a3d-4ea9-a59d-bd46d63d745e',
        method: 'GET',
        address: '{{net}}/ReportAppliance/getReportsWithAppliance/11',
      });
    });

    group('customAppliance', function () {
      postman[Request]({
        name: 'Get all custom appliances',
        id: 'f8635cf0-eaea-49c5-8d8b-16df60a9b445',
        method: 'GET',
        address: '{{net}}/customAppliance/all',
      });
    });
  });
}
